# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/output/mz_avnet_ooc_copy.xdc

# Block Designs: bd/mz_avnet/mz_avnet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet || ORIG_REF_NAME==mz_avnet} -quiet] -quiet

# IP: bd/mz_avnet/ip/mz_avnet_processing_system7_0_0/mz_avnet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet_processing_system7_0_0 || ORIG_REF_NAME==mz_avnet_processing_system7_0_0} -quiet] -quiet

# IP: bd/mz_avnet/ip/mz_avnet_proc_sys_reset_0_0/mz_avnet_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet_proc_sys_reset_0_0 || ORIG_REF_NAME==mz_avnet_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mz_avnet/ip/mz_avnet_proc_sys_reset_1_0/mz_avnet_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet_proc_sys_reset_1_0 || ORIG_REF_NAME==mz_avnet_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/mz_avnet/ip/mz_avnet_xlconcat_0_0/mz_avnet_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet_xlconcat_0_0 || ORIG_REF_NAME==mz_avnet_xlconcat_0_0} -quiet] -quiet

# IP: bd/mz_avnet/ip/mz_avnet_sds_irq_const_0/mz_avnet_sds_irq_const_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_avnet_sds_irq_const_0 || ORIG_REF_NAME==mz_avnet_sds_irq_const_0} -quiet] -quiet

# XDC: bd/mz_avnet/mz_avnet_ooc.xdc
