# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param bd.ForceAppCoreUpgrade 1
set_param general.maxThreads 1
set_param hd.Visual 0
set_param project.loadTopLevelOOCConstrs 1
create_project -in_memory -part xc7z007sclg225-1
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/iprepo/repo
  /tools/Xilinx/SDx/2018.3/data/ip/xilinx
  /tools/Xilinx/SDx/2018.3/data/cache/xilinx
  /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/.local/dsa/ipcache
  /tools/Xilinx/SDx/2018.3/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/bqpd/workspace_sdsoc/ip_cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/imports/hdl/mz_avnet_wrapper.v
add_files /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/mz_avnet.bd
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_processing_system7_0_0/mz_avnet_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_0_0/mz_avnet_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_0_0/mz_avnet_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_0_0/mz_avnet_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_1_0/mz_avnet_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_1_0/mz_avnet_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/ip/mz_avnet_proc_sys_reset_1_0/mz_avnet_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/mz_avnet/mz_avnet_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/output/mz_avnet_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/output/mz_avnet_ooc_copy.xdc]
set_property processing_order EARLY [get_files /home/bqpd/workspace_sdsoc/MiniZedMM/Debug/_sds/p0/vivado/output/mz_avnet_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mz_avnet_wrapper -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mz_avnet_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mz_avnet_wrapper_utilization_synth.rpt -pb mz_avnet_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
