# This file was automatically generated by SDx
write_user_impl_clock_constraint "" "processing_system7_0_FCLK_CLK0 {is_user_set false clk_id 0 freq 50.000000} processing_system7_0_FCLK_CLK1 {is_user_set false clk_id 1 freq 100.000000}" "" "../../../output"
