# This file was automatically generated by SDx
if { ![info exists _is_init_cmds] } {
  set vivado_error_file vivado_error.txt
  set vivado_warn_file vivado_warning.txt

  source ../../../.local/ocl_util.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}


# generate cookie file for messaging
write_cookie_file_impl ""

# utilization reports
report_utilization_impl false "none" "routed"


# run timing analysis and frequency scaling
if { ![report_timing_and_scale_freq "" "true" "dr" "../../../output" "kernel_clock_freqs {processing_system7_0_FCLK_CLK0 {is_user_set false clk_id 0 freq 50.000000} processing_system7_0_FCLK_CLK1 {is_user_set false clk_id 1 freq 100.000000}} system_clock_freqs {} worst_negative_slack 0 max_frequency 500 min_frequency 60 error_on_hold_violation true skip_timing_and_scaling false enable_auto_freq_scale false" ""] } {
  return false
}
